/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cr.ac.uned.estructurasdedatos.proyecto2.gui;

import cr.ac.uned.estructurasdedatos.proyecto2.logica.ArbolBinario;
import java.awt.Color;
import javax.swing.GroupLayout;

/**
 *
 * @author mayar
 */
public class PantallaPrincipal extends javax.swing.JFrame {
    
    private ArbolBinario arbolBinario;
    private PanelArbolBinario panelArbolBinario;

    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        initComponents();
        this.arbolBinario = new ArbolBinario();
        this.etiquetaMensajes.setForeground(Color.BLACK);
        this.etiquetaMensajes.setText("El árbol esta vació. Agregue una letra para empezar.");
        this.iniciarPanelArbolBinario();
    }
    
    /**
     * Método para iniciar el panel que pinta el árbol.
     */
    private void iniciarPanelArbolBinario() {
        this.panelArbolBinario = new PanelArbolBinario(arbolBinario);
        GroupLayout layout = new GroupLayout(this.panelArbolBinario);
        this.panelArbolBinario.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 479, Short.MAX_VALUE)
        );
        this.panelArbolBinario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Visualización del árbol", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));
        this.jScrollPane1.setViewportView(this.panelArbolBinario);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiquetaTitulo = new javax.swing.JLabel();
        campoLetra = new javax.swing.JTextField();
        etiquetaLetra = new javax.swing.JLabel();
        botonAgregar = new javax.swing.JButton();
        botonEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        etiquetaMensajes = new javax.swing.JLabel();
        botonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        etiquetaTitulo.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        etiquetaTitulo.setText("Árbol Binario de Búsqueda");

        campoLetra.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        campoLetra.setToolTipText("Digite solo 1 letra.");

        etiquetaLetra.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        etiquetaLetra.setText("Letra:");

        botonAgregar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        botonAgregar.setText("Agregar");
        botonAgregar.setToolTipText("Click para agregar la letra al árbol.");
        botonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarActionPerformed(evt);
            }
        });

        botonEliminar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        botonEliminar.setText("Eliminar");
        botonEliminar.setToolTipText("Click para eliminar la letra del árbol.");
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Visualización del árbol", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 494, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel1);

        etiquetaMensajes.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N

        botonSalir.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        botonSalir.setText("Salir");
        botonSalir.setToolTipText("click para salir de la aplicación");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(264, 264, 264)
                .addComponent(etiquetaTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(etiquetaLetra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoLetra, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonSalir))
                    .addComponent(etiquetaMensajes, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiquetaTitulo)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoLetra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaLetra)
                    .addComponent(botonAgregar)
                    .addComponent(botonEliminar)
                    .addComponent(botonSalir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etiquetaMensajes, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarActionPerformed
        boolean datosValidos = true;
        String letra = this.campoLetra.getText();
        if(letra == null || letra.trim().equals("")){
            datosValidos = false;
            this.etiquetaMensajes.setForeground(Color.RED);
            this.etiquetaMensajes.setText("La letra es requerida.");
        } else {
            if(letra.length() > 1) {
                datosValidos = false;
                this.etiquetaMensajes.setForeground(Color.RED);
                this.etiquetaMensajes.setText("Solo se permite 1 letra.");
            } else if(!letra.matches("[a-z|A-Z]")) {
                datosValidos = false;
                this.etiquetaMensajes.setForeground(Color.RED);
                this.etiquetaMensajes.setText("Solo se permiten letras de la \"A\" hasta la \"Z\".");
            } else if(this.arbolBinario.contieneElemento(letra)) {
                datosValidos = false;
                this.etiquetaMensajes.setForeground(Color.RED);
                this.etiquetaMensajes.setText("La letra ya existe en el árbol.");
            }
        }
        if(datosValidos){
            this.arbolBinario.agregarElemento(letra.toUpperCase());
            this.etiquetaMensajes.setForeground(Color.BLUE);
            this.etiquetaMensajes.setText("La letra \"" + letra + "\" ha sido agregada.");
            this.campoLetra.setText("");
            this.repaint();
        }
    }//GEN-LAST:event_botonAgregarActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_botonSalirActionPerformed

    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarActionPerformed
        boolean datosValidos = true;
        String letra = this.campoLetra.getText();
        if(letra == null || letra.trim().equals("")){
            datosValidos = false;
            this.etiquetaMensajes.setForeground(Color.RED);
            this.etiquetaMensajes.setText("La letra es requerida.");
        } else {
            if(letra.length() > 1) {
                datosValidos = false;
                this.etiquetaMensajes.setForeground(Color.RED);
                this.etiquetaMensajes.setText("Solo se permite 1 letra.");
            } else if(!letra.matches("[a-z|A-Z]")) {
                datosValidos = false;
                this.etiquetaMensajes.setForeground(Color.RED);
                this.etiquetaMensajes.setText("Solo se permiten letras de la \"A\" hasta la \"Z\".");
            } else if(!this.arbolBinario.contieneElemento(letra)) {
                datosValidos = false;
                this.etiquetaMensajes.setForeground(Color.RED);
                this.etiquetaMensajes.setText("La letra \"" + letra + "\" no existe en el árbol.");
            } else if(!this.arbolBinario.esHoja(letra)) {
                datosValidos = false;
                this.etiquetaMensajes.setForeground(Color.RED);
                this.etiquetaMensajes.setText("La letra \"" + letra + "\" no puede borrarse porque tiene elementos hijos.");
            }
        }
        if(datosValidos){
            this.arbolBinario.eliminarNodoHoja(letra.toUpperCase());
            this.etiquetaMensajes.setForeground(Color.BLUE);
            this.etiquetaMensajes.setText("La letra \"" + letra + "\" ha sido eliminada.");
            this.campoLetra.setText("");
            this.repaint();
        }
    }//GEN-LAST:event_botonEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregar;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton botonSalir;
    private javax.swing.JTextField campoLetra;
    private javax.swing.JLabel etiquetaLetra;
    private javax.swing.JLabel etiquetaMensajes;
    private javax.swing.JLabel etiquetaTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
